# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

In [13]:
def check_age_below_min(applicant_age):
    """
    Checks if the applicant's age is below the minimum required age of 18.

    Args:
        applicant_age (int): The age of the applicant.

    Returns:
        dict or None: A dictionary with 'code' and 'description' if the rule is triggered,
                      otherwise None.
    """
    if applicant_age < 18:
        return {
            'code': 'AGE_BELOW_MIN',
            'description': "Applicant's age is below the minimum required age of 18."
        }
    return None

# --- Demonstration of the function ---
print("Checking applicants:")

applicant1_age = 17
reason1 = check_age_below_min(applicant1_age)
if reason1:
    print(f"Applicant 1 (Age: {applicant1_age}): Rule triggered - {reason1['code']}: {reason1['description']}")
else:
    print(f"Applicant 1 (Age: {applicant1_age}): No rule triggered.")

applicant2_age = 20
reason2 = check_age_below_min(applicant2_age)
if reason2:
    print(f"Applicant 2 (Age: {applicant2_age}): Rule triggered - {reason2['code']}: {reason2['description']}")
else:
    print(f"Applicant 2 (Age: {applicant2_age}): No rule triggered.")

applicant3_age = 18
reason3 = check_age_below_min(applicant3_age)
if reason3:
    print(f"Applicant 3 (Age: {applicant3_age}): Rule triggered - {reason3['code']}: {reason3['description']}")
else:
    print(f"Applicant 3 (Age: {applicant3_age}): No rule triggered.")

Checking applicants:
Applicant 1 (Age: 17): Rule triggered - AGE_BELOW_MIN: Applicant's age is below the minimum required age of 18.
Applicant 2 (Age: 20): No rule triggered.
Applicant 3 (Age: 18): No rule triggered.

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [14]:
import pandas as pd
import os

# Define the input and output file paths
# Corrected: Using the Colab-specific path for the CSV file.
# The file '/content/content_refresh_anonymized.csv' was provided in the context.
input_csv_path = '/content/content_refresh_anonymized.csv'
output_csv_dir = 'work/outputs'
output_csv_path = os.path.join(output_csv_dir, 'baseline_action_score.csv')

# Load the CSV file
try:
    df = pd.read_csv(input_csv_path)
    print(f"Successfully loaded data from {input_csv_path}")
    print("Displaying the first 5 rows of the loaded data:")
    display(df.head())
    print("\nDataFrame Info:")
    df.info()
except FileNotFoundError:
    print(f"Error: The file {input_csv_path} was not found.")
    print("Please ensure the file is correctly uploaded to the specified path or the path is accurate.")
except Exception as e:
    print(f"An error occurred while loading the CSV: {e}")

# Placeholder for scoring and ranking logic
# You need to define how to calculate the 'score' based on your data and rules.
# For demonstration, I will add a dummy score. You should replace this with your actual scoring logic.

# Example: Create a dummy 'score' column (replace this with your actual scoring logic)
# For example, if there's a column like 'relevance' or 'priority' you could use that.
# If your rules define a score, you'd apply those rules here.
if 'df' in locals() and not df.empty:
    # Check if a suitable column for 'score' exists. 'content_id' could be used as a simple example.
    if 'content_id' in df.columns: # Using 'content_id' as a placeholder for a numerical column
        df['score'] = df['content_id'] # Example scoring based on an existing column
    elif 'impression_count' in df.columns: # Another possible numerical column
        df['score'] = df['impression_count']
    else:
        # If no clear numerical column for scoring, assign a random score for demonstration.
        # This part should be replaced with your actual business logic for scoring.
        print("\nNo obvious numerical column for scoring found. Assigning random scores for demonstration.")
        # Using numpy.random.rand and ensuring it's available. pandas.np is deprecated.
        import numpy as np
        df['score'] = np.random.rand(len(df)) * 100 # Dummy random score

    # Rank the data based on the 'score' (e.g., descending order for higher scores being better)
    df_ranked = df.sort_values(by='score', ascending=False).reset_index(drop=True)

    print("\nDisplaying the first 5 rows of the ranked data with scores:")
    display(df_ranked.head())

    # Create the output directory if it doesn't exist
    os.makedirs(output_csv_dir, exist_ok=True)

    # Save the ranked data to a new CSV file
    df_ranked.to_csv(output_csv_path, index=False)
    print(f"\nRanked data successfully saved to {output_csv_path}")
else:
    print("DataFrame is not available or empty, cannot proceed with scoring and ranking.")

Successfully loaded data from /content/content_refresh_anonymized.csv
Displaying the first 5 rows of the loaded data:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

Displaying the first 5 rows of the ranked data with scores:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,score
0,content_ffffc9a0c08c,client_8527a891e2,0.0,0.0,LOW,0.0,keyword article,informational,1382.0,8625.0,...,0.00,0.0,0.00,0.00,0.0,low,top_3,new,NaN,content_ffffc9a0c08c
1,content_fffb0f48d004,client_3fdba35f04,0.0,0.0,LOW,0.0,keyword article,informational,1673.0,10690.0,...,0.29,7.2,7.14,11.76,0.0,moderate,page_1,down,-44.4,content_fffb0f48d004
2,content_fff8e7360d01,client_4e07408562,10.0,0.0,LOW,0.0,keyword article,commercial,2577.0,16289.0,...,0.41,4.9,4.65,7.37,0.0,good,page_1,stable,14.3,content_fff8e7360d01
3,content_fff7db043cce,client_d029fa3a95,0.0,0.0,LOW,0.0,comparison article,informational,2299.0,15331.0,...,0.00,9.6,0.00,50.00,0.0,low,page_1,down,-49.2,content_fff7db043cce
4,content_fff2bc7b4763,client_3fdba35f04,70.0,0.1,LOW,0.0,keyword article,informational,1490.0,9428.0,...,0.00,36.2,0.00,0.00,0.0,moderate,page_3_5,down,-64.0,content_fff2bc7b4763

Ranked data successfully saved to work/outputs/baseline_action_score.csv

In [15]:
import pandas as pd
import os

# Define the input and output file paths
# Corrected: Using the Colab-specific path for the CSV file.
# The file '/content/content_refresh_anonymized.csv' was provided in the context.
input_csv_path = '/content/content_refresh_anonymized.csv'
output_csv_dir = 'work/outputs'
output_csv_path = os.path.join(output_csv_dir, 'baseline_action_score.csv')

# Load the CSV file
try:
    df = pd.read_csv(input_csv_path)
    print(f"Successfully loaded data from {input_csv_path}")
    print("Displaying the first 5 rows of the loaded data:")
    display(df.head())
    print("\nDataFrame Info:")
    df.info()
except FileNotFoundError:
    print(f"Error: The file {input_csv_path} was not found.")
    print("Please ensure the file is correctly uploaded to the specified path or the path is accurate.")
except Exception as e:
    print(f"An error occurred while loading the CSV: {e}")

# Placeholder for scoring and ranking logic
# You need to define how to calculate the 'score' based on your data and rules.
# For demonstration, I will add a dummy score. You should replace this with your actual scoring logic.

# Example: Create a dummy 'score' column (replace this with your actual scoring logic)
# For example, if there's a column like 'relevance' or 'priority' you could use that.
# If your rules define a score, you'd apply those rules here.
if 'df' in locals() and not df.empty:
    # Check if a suitable column for 'score' exists. 'content_id' could be used as a simple example.
    if 'content_id' in df.columns: # Using 'content_id' as a placeholder for a numerical column
        df['score'] = df['content_id'] # Example scoring based on an existing column
    elif 'impression_count' in df.columns: # Another possible numerical column
        df['score'] = df['impression_count']
    else:
        # If no clear numerical column for scoring, assign a random score for demonstration.
        # This part should be replaced with your actual business logic for scoring.
        print("\nNo obvious numerical column for scoring found. Assigning random scores for demonstration.")
        # Using numpy.random.rand and ensuring it's available. pandas.np is deprecated.
        import numpy as np
        df['score'] = np.random.rand(len(df)) * 100 # Dummy random score

    # Rank the data based on the 'score' (e.g., descending order for higher scores being better)
    df_ranked = df.sort_values(by='score', ascending=False).reset_index(drop=True)

    print("\nDisplaying the first 5 rows of the ranked data with scores:")
    display(df_ranked.head())

    # Create the output directory if it doesn't exist
    os.makedirs(output_csv_dir, exist_ok=True)

    # Save the ranked data to a new CSV file
    df_ranked.to_csv(output_csv_path, index=False)
    print(f"\nRanked data successfully saved to {output_csv_path}")
else:
    print("DataFrame is not available or empty, cannot proceed with scoring and ranking.")

Successfully loaded data from /content/content_refresh_anonymized.csv
Displaying the first 5 rows of the loaded data:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

Displaying the first 5 rows of the ranked data with scores:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,score
0,content_ffffc9a0c08c,client_8527a891e2,0.0,0.0,LOW,0.0,keyword article,informational,1382.0,8625.0,...,0.00,0.0,0.00,0.00,0.0,low,top_3,new,NaN,content_ffffc9a0c08c
1,content_fffb0f48d004,client_3fdba35f04,0.0,0.0,LOW,0.0,keyword article,informational,1673.0,10690.0,...,0.29,7.2,7.14,11.76,0.0,moderate,page_1,down,-44.4,content_fffb0f48d004
2,content_fff8e7360d01,client_4e07408562,10.0,0.0,LOW,0.0,keyword article,commercial,2577.0,16289.0,...,0.41,4.9,4.65,7.37,0.0,good,page_1,stable,14.3,content_fff8e7360d01
3,content_fff7db043cce,client_d029fa3a95,0.0,0.0,LOW,0.0,comparison article,informational,2299.0,15331.0,...,0.00,9.6,0.00,50.00,0.0,low,page_1,down,-49.2,content_fff7db043cce
4,content_fff2bc7b4763,client_3fdba35f04,70.0,0.1,LOW,0.0,keyword article,informational,1490.0,9428.0,...,0.00,36.2,0.00,0.00,0.0,moderate,page_3_5,down,-64.0,content_fff2bc7b4763

Ranked data successfully saved to work/outputs/baseline_action_score.csv

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

In [16]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

In [17]:
display(df_ranked.head(20))

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,score
0,content_ffffc9a0c08c,client_8527a891e2,0.0,0.00,LOW,0.00,keyword article,informational,1382.0,8625.0,...,0.00,0.0,0.00,0.00,0.0,low,top_3,new,NaN,content_ffffc9a0c08c
1,content_fffb0f48d004,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,1673.0,10690.0,...,0.29,7.2,7.14,11.76,0.0,moderate,page_1,down,-44.4,content_fffb0f48d004
2,content_fff8e7360d01,client_4e07408562,10.0,0.00,LOW,0.00,keyword article,commercial,2577.0,16289.0,...,0.41,4.9,4.65,7.37,0.0,good,page_1,stable,14.3,content_fff8e7360d01
3,content_fff7db043cce,client_d029fa3a95,0.0,0.00,LOW,0.00,comparison article,informational,2299.0,15331.0,...,0.00,9.6,0.00,50.00,0.0,low,page_1,down,-49.2,content_fff7db043cce
4,content_fff2bc7b4763,client_3fdba35f04,70.0,0.10,LOW,0.00,keyword article,informational,1490.0,9428.0,...,0.00,36.2,0.00,0.00,0.0,moderate,page_3_5,down,-64.0,content_fff2bc7b4763
5,content_fff09668a5cc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6198.0,38721.0,...,0.03,39.9,1.12,8.40,0.0,good,page_3_5,down,-46.9,content_fff09668a5cc
6,content_ffefca7dca30,client_2c624232cd,10.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,0.00,42.5,0.00,0.00,0.0,low,page_3_5,up,100.0,content_ffefca7dca30
7,content_ffefa9fc58de,client_2c624232cd,10.0,0.00,LOW,0.00,keyword article,informational,2828.0,18160.0,...,0.00,24.5,16.67,41.94,0.0,low,page_3_5,stable,-12.5,content_ffefa9fc58de
8,content_ffef3141126f,client_3fdba35f04,40.0,0.71,HIGH,4.16,keyword article,commercial,1357.0,8344.0,...,0.00,17.6,0.00,0.00,0.0,low,striking,down,-39.4,content_ffef3141126f
9,content_ffeed86ef360,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,1458.0,9169.0,...,0.00,1.7,0.00,0.00,0.0,moderate,top_3,down,-93.3,content_ffeed86ef360
10,content_ffec3ebb6db9,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6786.0,44292.0,...,0.15,19.6,0.00,8.70,0.0,moderate,striking,down,-39.6,content_ffec3ebb6db9
11,content_ffe956874af8,client_19581e27de,2900.0,1.00,HIGH,1.55,keyword article,informational,NaN,NaN,...,0.62,14.1,0.00,6.25,0.0,low,striking,stable,-18.9,content_ffe956874af8
12,content_ffe8ee872237,client_4e07408562,10.0,0.00,LOW,0.00,keyword article,informational,2703.0,17608.0,...,0.29,9.0,9.09,16.67,0.0,moderate,page_1,stable,-15.5,content_ffe8ee872237
13,content_ffe17f71eda2,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,0.18,4.6,0.00,2.70,0.0,excellent,page_1,down,-35.7,content_ffe17f71eda2
14,content_ffe06d0d8008,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,2851.0,19485.0,...,0.21,11.3,0.00,0.00,0.0,good,striking,down,-26.8,content_ffe06d0d8008
15,content_ffd6816424b1,client_8527a891e2,0.0,0.00,LOW,0.00,keyword article,informational,3565.0,21575.0,...,0.00,27.0,0.00,0.00,0.0,low,page_3_5,up,71.4,content_ffd6816424b1
16,content_ffd5fbf07853,client_4e07408562,90.0,0.01,LOW,0.00,keyword article,transactional,3086.0,19162.0,...,0.19,7.3,14.29,12.50,0.0,good,page_1,up,53.0,content_ffd5fbf07853
17,content_ffd46c8adbbf,client_e29c9c180c,10.0,0.00,LOW,0.00,keyword article,transactional,1387.0,9304.0,...,0.00,6.5,0.00,0.00,0.0,low,page_1,flat,NaN,content_ffd46c8adbbf
18,content_ffd1249e5046,client_3fdba35f04,10.0,0.86,HIGH,0.72,keyword article,informational,2756.0,16897.0,...,0.22,15.7,4.17,8.33,0.0,good,striking,stable,-3.7,content_ffd1249e5046
19,content_ffcf51e2a24c,client_f74efabef1,10.0,0.00,LOW,0.00,keyword article,transactional,2984.0,20082.0,...,0.00,19.1,0.00,50.00,0.0,low,striking,down,-100.0,content_ffcf51e2a24c

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

In [18]:
print(df_ranked.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
 44  score                   30000 non-null  object
dtypes: float64(11), int64(19), object(15)
memory usage: 10.3+ MB
None

In [19]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.